all:  main 

main: main.o buffer.o garis.o point.o warna.o pixel.o bentuk.o badanHeli.o ekorHeli.o helikopter.o city_map.o polygon.o awan.o clip.o fill_scan.o baling.o picker.o ledakan.o parasut.o
	g++ -o main main.o buffer.o garis.o point.o warna.o pixel.o  bentuk.o badanHeli.o ekorHeli.o helikopter.o city_map.o polygon.o awan.o clip.o fill_scan.o baling.o picker.o ledakan.o parasut.o

clean_main:
	rm *o main
