perspective: main_fill.o buffer.o warna.o point.o balok1tm.o fill_scan.o garis.o pixel.o
	g++ -o perspective main_fill.o buffer.o warna.o point.o balok1tm.o fill_scan.o garis.o pixel.o

clean:
	rm *o perspective
	
