polygon: mainPolygon.o polygon.o buffer.o garis.o pixel.o point.o warna.o 
	g++ -o polygon mainPolygon.o polygon.o buffer.o garis.o pixel.o point.o warna.o

canvas: mainCanvas.o canvas.o polygon.o buffer.o garis.o bentuk.o pixel.o point.o warna.o
	g++ -o canvas mainCanvas.o canvas.o polygon.o buffer.o garis.o bentuk.o pixel.o point.o warna.o	 

clean:
	rm *o canvas